# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# # Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = false

format = """
[│ ](bold purple)\
$git_branch\
$git_state\
$git_status\
$golang\
$rust\
$c\
$docker_context\
$lua\
$node_js\
$package\
$cmd_duration\
$line_break\
[│ ](bold purple)\
$username\
$hostname\
$directory\
$character"""

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_status]
format = "[[(* $conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead$behind$stashed)]($style)"
style = "cyan"
conflicted = "⚑ "
renamed = " "
deleted = "✖ "
ahead = "↑·"
behind = "↓·"
staged = "● "
modified = "✚ "
untracked = "… "
stashed = "≡ "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[c]
symbol = " "

[directory]
read_only = " "
style = "blue"

[docker_context]
symbol = " "

[git_branch]
# symbol = " "
symbol = "⎇  "
style = "green"

[golang]
symbol = " "

[lua]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "

